### ISSUE TITLE
Float issue when using compute_nuclear_attraction

### ISSUE THREAD

**Issue by PeaWagon** [theochem/cgbasis#22]
Hi guys. I'm trying to use gbasis within the density matrix code. I ran into a type conversion error. Any suggestions on how I can fix it? Does it have anything to do with the version of numpy I am using (currently 1.14.3)? Please find my output below. The code itself is on the quantum elephant repo (densitymatrices).

```
(var2dm) ❯ nosetests -v var2DM
test_misc.test_prep_electron_int ... /home/jenefre/miniconda3/envs/var2dm/lib/python3.6/site-packages/gbasis/utils.py:76: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if coordinates.shape != (natom, 3) or not np.issubdtype(coordinates.dtype, np.float):
ERROR

======================================================================
ERROR: test_misc.test_prep_electron_int
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenefre/miniconda3/envs/var2dm/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/jenefre/Documents/githubcode/densitymatrices/var2DM/test/test_misc.py", line 12, in test_prep_electron_int
    mol.pseudo_numbers, '3-21G')
  File "/home/jenefre/Documents/githubcode/densitymatrices/var2DM/misc.py", line 73, in prep_electron_int
    na = obasis.compute_nuclear_attraction(coords, nums, chrgs)
  File "gbasis/cext.pyx", line 693, in gbasis.cext.GOBasis.compute_nuclear_attraction
ValueError: Buffer dtype mismatch, expected 'double' but got 'long'

----------------------------------------------------------------------
Ran 1 test in 0.026s

FAILED (errors=1)
```

**Comment by xiaominhc** [comment]
I think you only need to call the function with coordinates and charges, so 
na = obasis.compute_nuclear_attraction(coords, chrgs)

**Comment by PeaWagon** [comment]
Thanks that worked. :)
